language: node_js
node_js:
  - stable
before_script:
  - npm install -g @angular-cli
  - npm install angular-cli-ghpages --save-dev
script:
  - ng build --prod --base-href "/githubReposetorySeach/"
  - npx ngh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: true
  on:
    branch: master
