language: node_js
node_js:
  - stable

script:
  - ng build --prod --base-href "/githubReposetorySeach/"
  - npx ngh --dir=dist/searchGithubRepositories
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: true
  on:
    branch: master
